version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rag_api
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  rag_api:
    image: registry.librechat.ai/danny-avila/librechat-rag-api-dev:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_DB=rag_api
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - RAG_PORT=${RAG_PORT:-8000}
    ports:
      - "${RAG_PORT}:${RAG_PORT}"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  pgdata:
