{{ if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: lemefy-rag-db
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}
  postgres-password: {{ randAlphaNum 32 | b64enc | quote }}
{{ end }}
