CREATE DATABASE rag_api;
CREATE DATABASE kaneo;
CREATE DATABASE lemefy;
CREATE DATABASE temporal;

CREATE USER myuser WITH PASSWORD '${RAG_DB_PASSWORD:-mypassword}';
CREATE USER kaneo WITH PASSWORD '${KANEO_DB_PASSWORD:-kaneo_password}';
CREATE USER lemefy WITH PASSWORD '${LEMEFY_DB_PASSWORD:-lemefy_password}';

GRANT ALL PRIVILEGES ON DATABASE rag_api TO myuser;
GRANT ALL PRIVILEGES ON DATABASE kaneo TO kaneo;
GRANT ALL PRIVILEGES ON DATABASE lemefy TO lemefy;
